/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElImg: typeof import('element-plus/es')['ElImg']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSkeletonItem: typeof import('element-plus/es')['ElSkeletonItem']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    GameDetail: typeof import('./src/components/GameDetail.vue')['default']
    GameItem: typeof import('./src/components/GameItem.vue')['default']
    GameList: typeof import('./src/components/GameList.vue')['default']
    Querry: typeof import('./src/components/Querry.vue')['default']
    SummonerInfo: typeof import('./src/components/SummonerInfo.vue')['default']
    UserInfo: typeof import('./src/components/UserInfo.vue')['default']
  }
  export interface ComponentCustomProperties {
    vInfiniteScroll: typeof import('element-plus/es')['ElInfiniteScroll']
  }
}
